[versions]
testcontainers = "1.20.0"
quarkus = "3.12.3"
jdbi = "3.45.4"
yasson = "3.0.4"
bcprov = "1.78.1"

[libraries]
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
quarkus-platform-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
jdbi-core = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi" }
yasson = { module = "org.eclipse:yasson", version.ref = "yasson" }
bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprov" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
