name: ci

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  check:
    runs-on: 'ubuntu-latest'
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: muyun2024
          POSTGRES_DB: muyun
        ports:
          - 54324:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Checkstyle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: checkstyleMain checkstyleTest
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: check
